### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by DmitrijVC** [sterzidev/DTG#1]
_That is some pro level scamming techniques._ 

### But now seriously
Discord is a pice of crap. If You can make someone to open an exe file from You, can just write a simple grabber. That thing you just did is more like a phising I guess. You can just take tokens in plain text from a local .ldb files. 

Quick edit. 
If I would be the victim, I will probably just spam the hell out of that webhook with some "gay content" (you know what I mean)

**Comment by sterzidev** [comment]
this is my old shitty token grabber, i never used this for steal and something more. I was find this on my pc and i want to publish it for someone who want this.
